### PR TITLE
Create dependabot.yml

### LINKED ISSUE #52: Automatic update to Dependencies using Dependabot.
Using outdated packages raises security concerns and updating the packages is an essential step. But this step can be automated.
Updates to packages can no longer need to be a manual task. Dependabot can be used to identify the dependencies that have update and it can raise a PR.

### PR DESCRIPTION
**Pull request by The-Reverse-Flash**
Automatic update to Dependencies using Dependabot.
Added Dependabot configuration to automatically check for updates on packages on a weekly basis. It will also create a PR whenever there is an update. 
Fixes: [Issue - 52](https://github.com/hacktobered/hacktobered.com/issues/52)

### CODE REVIEW

**Comment by ankitwww** [comment]
Thanks for your help @The-Reverse-Flash

**Comment by The-Reverse-Flash** [comment]
@ankitwww : Thank you. Can you also please add the label:hacktoberfest-accepted

**Comment by ankitwww** [comment]
I guess it's not needed, as the repo itself is tagged well. still gonna add that now...

**Comment by The-Reverse-Flash** [comment]
@ankitwww Thank you so much.  😊

**Pull request merged**
