### PR TITLE
hotfix: remove share button

### PR DESCRIPTION
**Pull request by pedroagcf**

### CODE REVIEW

**Comment by ankitwww** [comment]
Hey @pedroagcf . Thanks for the PR. It seems I missed communicating clearly the requirement in #11 
We need to remove the Share button from card "So that it won't appear in the downloaded image itself" 
Looks like currently you removed the button entirely from the page.

- We need the button so that the user can share the card, however it does not need to be part of the card - otherwise the button will also appear in the card. e.g. see this screenshot - the button also appears in the card (ideally it should not be part of the shared image/card):

my-node


Please let me know if you have any questions on above, or need further clarification. Happy to help!

**Comment by pedroagcf** [comment]
So the button should be keep as we already have. The real problem is that the button is appearing in the png, right? @ankitwww

**Comment by ankitwww** [comment]
@pedroagcf  Yeah! It should not appear in the PNG. however it should be on the page/card so that the user can click it to download the PNG. 
Just try pushing the Flex (which contains button) out of the stacks which has Id... that might fix that, didn't try though

**Comment by pedroagcf** [comment]
image looks good? @ankitwww

**Comment by ankitwww** [comment]
Perfect! Going to merge this.

**Pull request merged**
