### PR TITLE
feat: how to contribute tutorial

### PR DESCRIPTION
**Pull request by pedroagcf**

### CODE REVIEW

**Comment by pedroagcf** [comment]
Hey @ankitwww, I can't pull the updates from the main branch and I can't manage the conflicts so could you please, help me?

**Comment by ankitwww** [comment]
Sure, I will take a look by either tonight  or tomorrow early morning

**Comment by pedroagcf** [comment]
sure! can you please add some label here?

**Comment by ankitwww** [comment]
And now we are good!

**Pull request merged**
