### PR TITLE
fix: height issue solved

### PR DESCRIPTION
**Pull request by nishtha53**
Issue of height is solved.
Equally height is taken for all cards.

### CODE REVIEW

**Comment by nishtha53** [comment]
@ankitwww Thankyou for merging my PR. It was great experience to contribute. 🚀

**Comment by nishtha53** [comment]
@ankitwww just one favour would you please add hacktoberfest-accepted label please.

**Comment by ankitwww** [comment]
Great work! And thanks for your help.

**Comment by ankitwww** [comment]
I guess it's not needed, as the repo itself is tagged well. still gonna add that now...

**Comment by nishtha53** [comment]
@ankitwww ohh okay thankyou for adding

**Pull request merged**
