### PR TITLE
feat: add privacy policy page

### PR DESCRIPTION
**Pull request by pedroagcf**

### CODE REVIEW

**Comment by pedroagcf** [comment]
@ankitwww, do you know what could be the reason? I can't see the logs

**Comment by ankitwww** [comment]
Yes, here are the logs. You can see them locally by building the project. 'npm run build'


image

**Comment by ankitwww** [comment]
@pedroagcf let me know if you need any further details for error

**Comment by pedroagcf** [comment]
looks better now! let me know if It is ok for you @ankitwww

**Comment by ankitwww** [comment]
Pretty good! Thank @pedroagcf

**Comment by pedroagcf** [comment]
could you please add the Hacktoberfest label for this PR? @ankitwww

**Comment by ankitwww** [comment]
I guess we don't need to tag PR as the whole repo is tagged - so basically every PR is automatically accepted in hacktoberfest. 
Still, no worries, I will add accepted tag now

**Pull request merged**
