### PR TITLE
Automatic update to Dependencies using Dependabot.

### LINKED ISSUE #52: Automatic update to Dependencies using Dependabot.
Using outdated packages raises security concerns and updating the packages is an essential step. But this step can be automated.
Updates to packages can no longer need to be a manual task. Dependabot can be used to identify the dependencies that have update and it can raise a PR.

### PR DESCRIPTION
**Pull request by The-Reverse-Flash**
Added Dependabot configuration to automatically check for updates on packages on a weekly basis. It will also create a PR whenever there is an update. 
Fixes: [Issue - 52](https://github.com/hacktobered/hacktobered.com/issues/52)

### CODE REVIEW

**Comment by The-Reverse-Flash** [comment]
Is some thing wrong with the deployment ? 
Unable to see the errors.

**Comment by The-Reverse-Flash** [comment]
Looks like this workflow is awaiting approval.

( This workflow is awaiting approval from a maintainer in https://github.com/hacktobered/hacktobered.com/pull/53 )

**Comment by ankitwww** [comment]
Hey @The-Reverse-Flash - looks like you closed this PR. Please open and I can take a look

**Comment by ankitwww** [comment]
@The-Reverse-Flash thanks for reopening. Looks like the file was reverted and currently there are no changes to merge. I guess you need to re-commit the file

**Comment by ankitwww** [comment]
image

**Comment by The-Reverse-Flash** [comment]
@ankitwww : Oops. that was done by mistake.. Reopened it. please check.

**Comment by The-Reverse-Flash** [comment]
sorry for the trouble.. working on it

**Comment by The-Reverse-Flash** [comment]
Closed this as i created new [PR](https://github.com/hacktobered/hacktobered.com/pull/55)

**Pull request closed without merging**
