### PR TITLE
add sign out on the mobile navbar

### PR DESCRIPTION
**Pull request by tinuh**
#2

### CODE REVIEW

**Comment by tinuh** [comment]
hey, can you let me know what the problem was on vercel? I suspect it's a type issue

**Comment by ankitwww** [comment]
Try "npm run build" locally once. You should see the error locally.
If you don't see - let me know - I will send you Vercel logs

**Comment by tinuh** [comment]
sure got it!

**Comment by tinuh** [comment]
alright that should have fixed the build issue

**Pull request merged**
